#!'C:\Users\php 3\AppData\Local\Programs\Python\Python37-32\python.exe'
print('Content-type:text/html\r\n\r\n')
print('<html>')
print('<head>')
print('<title>First CGI</title>')
print('</head>')
print('<body>')
print('<h2> This is a test Page</h2>')
print('</body>')
print('</html>')