import tkinter
from tkinter import *
from tkinter import messagebox
a=tkinter.Tk()
a.title("CALCULATOR")
def num(num):
    t0.insert("end",num)
def eql():
    ans=str(eval(t0.get()))
    t0.delete(0, "end")
    t0.insert("end",ans)
def clr():
    t0.delete(0,"end")
def ext():
    messagebox.showinfo("Exit","Do you want to exit??")
    a.quit()
t0=tkinter.Entry(a,bg="pink",width=30)
t0.grid(row=0,column=0,padx=10,pady=10,columnspan=4)
b0=tkinter.Button(a,text="0",padx=20,pady=10,command=lambda :num(0))
b0.grid(row=4,column=0)
b1=tkinter.Button(a,text="1",padx=20,pady=10,command=lambda :num(1))
b1.grid(row=3,column=0)
b2=tkinter.Button(a,text="2",padx=20,pady=10,command=lambda :num(2))
b2.grid(row=3,column=1)
b3=tkinter.Button(a,text="3",padx=20,pady=10,command=lambda :num(3))
b3.grid(row=3,column=2)
b4=tkinter.Button(a,text="4",padx=20,pady=10,command=lambda :num(4))
b4.grid(row=2,column=0)
b5=tkinter.Button(a,text="5",padx=20,pady=10,command=lambda :num(5))
b5.grid(row=2,column=1)
b6=tkinter.Button(a,text="6",padx=20,pady=10,command=lambda :num(6))
b6.grid(row=2,column=2)
b7=tkinter.Button(a,text="7",padx=20,pady=10,command=lambda :num(7))
b7.grid(row=1,column=0)
b8=tkinter.Button(a,text="8",padx=20,pady=10,command=lambda :num(8))
b8.grid(row=1,column=1)
b9=tkinter.Button(a,text="9",padx=20,pady=10,command=lambda :num(9))
b9.grid(row=1,column=2)
add=tkinter.Button(a,text="+",padx=20,pady=10,command=lambda :num("+"))
add.grid(row=1,column=3)
sub=tkinter.Button(a,text="-",padx=20,pady=10,command=lambda :num("-"))
sub.grid(row=2,column=3)
mul=tkinter.Button(a,text="*",padx=20,pady=10,command=lambda :num("*"))
mul.grid(row=3,column=3)
div=tkinter.Button(a,text="/",padx=20,pady=10,command=lambda :num("/"))
div.grid(row=4,column=3)
cl=tkinter.Button(a,text="C",padx=20,pady=10,command=clr,bg="orange")
cl.grid(row=4,column=1)
eq=tkinter.Button(a,text="=",padx=20,pady=10,command=eql,bg="green")
eq.grid(row=4,column=2)
ex=tkinter.Button(a,text="Exit",padx=20,pady=10,command=ext)
ex.grid(row=5,column=3)
a.mainloop()
