import tkinter
from tkinter import *
a=tkinter.Tk()
a.minsize(400,600)
a.title("Menu")
men=Menu(a)
filem=Menu(men,tearoff=0)
filem.add_command(label="New")
filem.add_command(label="Save")
filem.add_separator()
filem.add_command(label="Exit",command=a.quit)
men.add_cascade(label="File",menu=filem)
editm=Menu(men,tearoff=0)
editm.add_command(label="Copy")
editm.add_command(label="Paste")
editm.add_separator()
editm.add_command(label="Exit",command=a.quit)
men.add_cascade(label="Edit",menu=editm)
a.config(menu=men)
a.mainloop()