import tkinter
from tkinter import *
a=tkinter.Tk()
a.title("Frame")
b=Frame(width=200,height=200,highlightbackground="black",highlightthickness=3,bg="pink")
b.grid(row=0,column=0,padx=10,pady=10,ipadx=20,ipady=20)
b1=tkinter.Label(b,text="User Name :",pady=10,bg="pink",padx=13)
b1.grid(row=0,column=0)
c=tkinter.Entry(b,bg="lightblue")
c.grid(row=0,column=1)
b2=tkinter.Label(b,text="Password :",bg="pink",pady=10,padx=13)
b2.grid(row=1,column=0)
d=tkinter.Entry(b,bg="lightblue")
d.grid(row=1,column=1)

g=Frame(width=200,height=200,highlightbackground="red",highlightthickness=3,bg="pink")
g.grid(row=0,column=1,padx=10,pady=10,ipadx=20,ipady=20)
b11=tkinter.Label(g,text="User Name :",bg="pink",pady=10,padx=13)
b11.grid(row=0,column=0)
c1=tkinter.Entry(g,bg="yellow")
c1.grid(row=0,column=1)
b22=tkinter.Label(g,text="Password :",bg="pink",pady=10,padx=13)
b22.grid(row=1,column=0)
d1=tkinter.Entry(g,bg="yellow")
d1.grid(row=1,column=1)
a.mainloop()